name: Deploy Backend

on:
  push:
    branches: [main]
    # paths: ["frontend/**", "backend/**"]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6.3.0
        with:
          node-version: 22.x.x

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies frontend
        working-directory: ./frontend
        run: pnpm install

      - name: Build frontend
        working-directory: ./frontend
        run: pnpm run build

      - name: Install dependencies backend
        working-directory: ./backend
        run: pnpm install

      - name: Build backend
        working-directory: ./backend
        run: pnpm run build

      - name: Copy frontend build to backend
        run: mkdir -p ./backend/dist/frontend && cp -r ./frontend/dist/* ./backend/dist/frontend/

      - name: Azure CLI version check
        run: az --version

      - name: Configure App Settings
        run: |
          az webapp config appsettings set \
            --name bytelift \
            --resource-group bytelift-rg \
            --settings \
              PORT=8080 \
              NODE_ENV=production \
              DB_USER="${{ secrets.DB_USER }}" \
              DB_HOST="${{ secrets.DB_HOST }}" \
              DB_NAME="${{ secrets.DB_NAME }}" \
              DB_PORT="${{ secrets.DB_PORT }}" \
              DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              DB_CA="${{ secrets.DB_CA }}" \
              JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              CLOUDINARY_CLOUD_NAME="${{ secrets.CLOUDINARY_CLOUD_NAME }}" \
              CLOUDINARY_API_KEY="${{ secrets.CLOUDINARY_API_KEY }}" \
              CLOUDINARY_API_SECRET="${{ secrets.CLOUDINARY_API_SECRET }}"

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: bytelift
          package: ./backend/dist
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
