name: Deploy Backend

on:
  push:
    branches: [main]
    paths: ["frontend/**", "backend/**"]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v6.3.0
        with:
          node-version: 22.x.x

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies frontend
        working-directory: ./frontend
        run: pnpm install

      - name: Build frontend
        working-directory: ./frontend
        run: pnpm run build

      - name: Install dependencies backend
        working-directory: ./backend
        run: pnpm install

      - name: Build backend
        working-directory: ./backend
        run: pnpm run build

      - name: Copy frontend build to backend
        run: mkdir -p ./backend/dist/frontend && cp -r ./frontend/dist/* ./backend/dist/frontend/

      - name: Configure App Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: bytelift
          app-settings-json: |
            [
              {"name": "PORT", "value": "8080"},
              {"name": "NODE_ENV", "value": "production"},
              {"name": "DB_USER", "value": "${{ secrets.DB_USER }}"},
              {"name": "DB_HOST", "value": "${{ secrets.DB_HOST }}"},
              {"name": "DB_NAME", "value": "${{ secrets.DB_NAME }}"},
              {"name": "DB_PORT", "value": "${{ secrets.DB_PORT }}"},
              {"name": "DB_PASSWORD", "value": "${{ secrets.DB_PASSWORD }}"},
              {"name": "DB_CA", "value": "${{ secrets.DB_CA }}"},
              {"name": "JWT_SECRET", "value": "${{ secrets.JWT_SECRET }}"},
              {"name": "CLOUDINARY_CLOUD_NAME", "value": "${{ secrets.CLOUDINARY_CLOUD_NAME }}"},
              {"name": "CLOUDINARY_API_KEY", "value": "${{ secrets.CLOUDINARY_API_KEY }}"},
              {"name": "CLOUDINARY_API_SECRET", "value": "${{ secrets.CLOUDINARY_API_SECRET }}"}
            ]

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: bytelift
          package: ./backend/dist
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
